schema_version = "1.0.0"

id = "data_scale"
version = "1.0.2"
name = "Data Scale"
tagline = "Quickly inspect the size of datablocks"
maintainer = "hisanimations <hisprofile029@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Temporarily create .blend files to weigh them"